# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    target_branch: 13.x
    milestone: 3
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    target_branch: 13.x
    milestone: 3
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    target_branch: 12.x
    milestone: 2
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    target_branch: 12.x
    milestone: 2
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    target_branch: 11.x
    milestone: 1
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    target_branch: 11.x
    milestone: 1
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    versioning-strategy: "increase"
