# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    milestone: 4
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Dependabot] "

  - package-ecosystem: "composer"
    milestone: 4
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "georgringer/autoswitchtolistview"
        versions: [ "3.1.0" ]
    versioning-strategy: "increase"
    commit-message:
      prefix: "[Dependabot] "
