#!/bin/bash

## Description: Clean up temporary data from the functional tests
## Usage: tests-cleanup
## Example: "ddev tests-cleanup"

rm -rf public/typo3temp/var/tests/
echo 'Finished removing temporary test directories.'

mariadb --skip-column-names <<< 'SELECT CONCAT("DROP DATABASE ", SCHEMA_NAME, ";") FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME LIKE "%test%";' | mariadb --verbose
echo 'Finished removing test databases.'
