name: typo3-testing-12-4
type: typo3
docroot: public
php_version: "8.3"
webserver_type: apache-fpm
router_http_port: "8080"
router_https_port: "8081"
xdebug_enabled: false
additional_hostnames:
  - "typo3-testing-12-5-en"
additional_fqdns: [ ]
database:
  type: mariadb
  version: "10.6"
use_dns_when_possible: true
timezone: Europe/Berlin
composer_version: "2.6"
web_environment: [ ]
nodejs_version: "22"

# This config.yaml was created with ddev version v1.17.7
