base: 'https://typo3-testing-10-4.ddev.site:8081/'
baseVariants: { }
errorHandling: { }
languages:
  - title: Deutsch
    enabled: true
    base: 'https://typo3-testing-10-4.ddev.site:8081'
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    languageId: '0'
  - title: Englisch
    enabled: true
    base: 'https://typo3-testing-10-4-en.ddev.site:8081'
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: Englisch
    hreflang: en-US
    direction: ''
    fallbackType: fallback
    fallbacks: '0'
    flag: en-us-gb
    languageId: '1'
rootPageId: 1
routes: { }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: '/'
    index: ''
    map:
      '/': 0
  EventSingleView:
    type: Plugin
    limitToPages:
      - 17
    routePath: '/{slug}'
    namespace: 'tx_seminars_pi1'
    _arguments:
      slug: showUid
    requirements:
      slug: '[a-z0-9/\-]+'
    aspects:
      slug:
        type: PersistedAliasMapper
        tableName: 'tx_seminars_seminars'
        routeFieldName: 'slug'
  EventRegistration:
    type: Extbase
    limitToPages:
      - 18
    extension: Seminars
    plugin: EventRegistration
    defaultController: 'EventRegistration::checkPrerequisites'
    routes:
      - routePath: '/check/{event}'
        _controller: 'EventRegistration::checkPrerequisites'
        _arguments:
          event: event
      - routePath: '/new/{event}'
        _controller: 'EventRegistration::new'
        _arguments:
          event: event
    aspects:
      event:
        type: PersistedAliasMapper
        tableName: 'tx_seminars_seminars'
        routeFieldName: 'uid'
      registration:
        type: PersistedAliasMapper
        tableName: 'tx_seminars_attendances'
        routeFieldName: 'uid'
