base: 'https://typo3-testing-10-4.ddev.site:8081/'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: Deutsch
    enabled: true
    base: 'https://typo3-testing-10-4.ddev.site:8081'
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    languageId: '0'
  -
    title: Englisch
    enabled: true
    base: 'https://typo3-testing-10-4-en.ddev.site:8081'
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: Englisch
    hreflang: en-US
    direction: ''
    fallbackType: fallback
    fallbacks: '0'
    flag: en-us-gb
    languageId: '1'
rootPageId: 1
routes: {  }
